In [1]:
# Income prediction using files from pm-se-onboarding-nick (git user nmball42)
# Uploaded to new public repo income-prediction on nmball42
# Same procedure can be used for any other new project if can be in public repo
# Run in Oracle ADSCS Py2.7 Standard environment on demo-next.datascience.com

# Data from https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.{data,test}.txt
# In ~/Oracle/data/income/ on laptop
# Renamed there as income_{train,test}.csv
# Data uploaded to project repo files so can access from this notebook

# Nov 08th 2018

In [2]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint as sp_randint

In [3]:
data_dir = ''
col_names = ['age','workclass','fnlwgt','education','education-num','marital-status','occupation','relationship','race','sex','capital-gain','capital-loss','hours-per-week','native-country','yearly-income']

In [4]:
data_train = pd.read_csv(data_dir + 'income_train.csv', names = col_names)

In [5]:
data_train

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,yearly-income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
11,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
12,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
13,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
14,40,Private,121772,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,?,>50K
15,34,Private,245487,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
16,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
17,32,Private,186824,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
18,38,Private,28887,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
19,43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K
20,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
21,54,Private,302146,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
22,35,Federal-gov,76845,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States,<=50K
23,43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K
24,59,Private,109015,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
25,56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
26,19,Private,168294,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
27,54,?,180211,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
28,39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K
29,49,Private,193366,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32531,30,?,33811,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Female,0,0,99,United-States,<=50K
32532,34,Private,204461,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
32533,54,Private,337992,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0,0,50,Japan,>50K
32534,37,Private,179137,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,39,United-States,<=50K
32535,22,Private,325033,12th,8,Never-married,Protective-serv,Own-child,Black,Male,0,0,35,United-States,<=50K
32536,34,Private,160216,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,55,United-States,>50K
32537,30,Private,345898,HS-grad,9,Never-married,Craft-repair,Not-in-family,Black,Male,0,0,46,United-States,<=50K
32538,38,Private,139180,Bachelors,13,Divorced,Prof-specialty,Unmarried,Black,Female,15020,0,45,United-States,>50K
32539,71,?,287372,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,>50K
32540,45,State-gov,252208,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K
32541,41,?,202822,HS-grad,9,Separated,?,Not-in-family,Black,Female,0,0,32,United-States,<=50K
32542,72,?,129912,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,25,United-States,<=50K
32543,45,Local-gov,119199,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,0,0,48,United-States,<=50K
32544,31,Private,199655,Masters,14,Divorced,Other-service,Not-in-family,Other,Female,0,0,30,United-States,<=50K
32545,39,Local-gov,111499,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States,>50K
32546,37,Private,198216,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,White,Female,0,0,40,United-States,<=50K
32547,43,Private,260761,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,Mexico,<=50K
32548,65,Self-emp-not-inc,99359,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K
32549,43,State-gov,255835,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K
32550,43,Self-emp-not-inc,27242,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,<=50K
32551,32,Private,34066,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K
32552,43,Private,84661,Assoc-voc,11,Married-civ-spouse,Sales,Husband,White,Male,0,0,45,United-States,<=50K
32553,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
32554,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
32555,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [6]:
data_test = pd.read_csv(data_dir + 'income_test.csv', names = col_names, skiprows = 1)

In [7]:
### Remove period in last col of test ###

In [8]:
data_test

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,yearly-income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K.
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K.
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K.
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K.
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K.
5,34,Private,198693,10th,6,Never-married,Other-service,Not-in-family,White,Male,0,0,30,United-States,<=50K.
6,29,?,227026,HS-grad,9,Never-married,?,Unmarried,Black,Male,0,0,40,United-States,<=50K.
7,63,Self-emp-not-inc,104626,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,3103,0,32,United-States,>50K.
8,24,Private,369667,Some-college,10,Never-married,Other-service,Unmarried,White,Female,0,0,40,United-States,<=50K.
9,55,Private,104996,7th-8th,4,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,10,United-States,<=50K.
10,65,Private,184454,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,6418,0,40,United-States,>50K.
11,36,Federal-gov,212465,Bachelors,13,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States,<=50K.
12,26,Private,82091,HS-grad,9,Never-married,Adm-clerical,Not-in-family,White,Female,0,0,39,United-States,<=50K.
13,58,?,299831,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,35,United-States,<=50K.
14,48,Private,279724,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,3103,0,48,United-States,>50K.
15,43,Private,346189,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,50,United-States,>50K.
16,20,State-gov,444554,Some-college,10,Never-married,Other-service,Own-child,White,Male,0,0,25,United-States,<=50K.
17,43,Private,128354,HS-grad,9,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,30,United-States,<=50K.
18,37,Private,60548,HS-grad,9,Widowed,Machine-op-inspct,Unmarried,White,Female,0,0,20,United-States,<=50K.
19,40,Private,85019,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,45,?,>50K.
20,34,Private,107914,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,47,United-States,>50K.
21,34,Private,238588,Some-college,10,Never-married,Other-service,Own-child,Black,Female,0,0,35,United-States,<=50K.
22,72,?,132015,7th-8th,4,Divorced,?,Not-in-family,White,Female,0,0,6,United-States,<=50K.
23,25,Private,220931,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,43,Peru,<=50K.
24,25,Private,205947,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K.
25,45,Self-emp-not-inc,432824,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,7298,0,90,United-States,>50K.
26,22,Private,236427,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K.
27,23,Private,134446,HS-grad,9,Separated,Machine-op-inspct,Unmarried,Black,Male,0,0,54,United-States,<=50K.
28,54,Private,99516,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,35,United-States,<=50K.
29,32,Self-emp-not-inc,109282,Some-college,10,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,60,United-States,<=50K.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16251,81,?,26711,Assoc-voc,11,Married-civ-spouse,?,Husband,White,Male,2936,0,20,United-States,<=50K.
16252,60,Private,117909,Assoc-voc,11,Married-civ-spouse,Prof-specialty,Husband,White,Male,7688,0,40,United-States,>50K.
16253,39,Private,229647,Bachelors,13,Never-married,Tech-support,Not-in-family,White,Female,0,1669,40,United-States,<=50K.
16254,38,Private,149347,Masters,14,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,>50K.
16255,43,Local-gov,23157,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,1902,50,United-States,>50K.
16256,23,Private,93977,HS-grad,9,Never-married,Machine-op-inspct,Own-child,White,Male,0,0,40,United-States,<=50K.
16257,73,Self-emp-inc,159691,Some-college,10,Divorced,Exec-managerial,Not-in-family,White,Female,0,0,40,United-States,<=50K.
16258,35,Private,176967,Some-college,10,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,<=50K.
16259,66,Private,344436,HS-grad,9,Widowed,Sales,Other-relative,White,Female,0,0,8,United-States,<=50K.
16260,27,Private,430340,Some-college,10,Never-married,Sales,Not-in-family,White,Female,0,0,45,United-States,<=50K.
16261,40,Private,202168,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,15024,0,55,United-States,>50K.
16262,51,Private,82720,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K.
16263,22,Private,269623,Some-college,10,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K.
16264,64,Self-emp-not-inc,136405,HS-grad,9,Widowed,Farming-fishing,Not-in-family,White,Male,0,0,32,United-States,<=50K.
16265,50,Local-gov,139347,Masters,14,Married-civ-spouse,Prof-specialty,Wife,White,Female,0,0,40,?,>50K.
16266,55,Private,224655,HS-grad,9,Separated,Priv-house-serv,Not-in-family,White,Female,0,0,32,United-States,<=50K.
16267,38,Private,247547,Assoc-voc,11,Never-married,Adm-clerical,Unmarried,Black,Female,0,0,40,United-States,<=50K.
16268,58,Private,292710,Assoc-acdm,12,Divorced,Prof-specialty,Not-in-family,White,Male,0,0,36,United-States,<=50K.
16269,32,Private,173449,HS-grad,9,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,0,0,40,United-States,<=50K.
16270,48,Private,285570,HS-grad,9,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States,<=50K.
16271,61,Private,89686,HS-grad,9,Married-civ-spouse,Sales,Husband,White,Male,0,0,48,United-States,<=50K.
16272,31,Private,440129,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K.
16273,25,Private,350977,HS-grad,9,Never-married,Other-service,Own-child,White,Female,0,0,40,United-States,<=50K.
16274,48,Local-gov,349230,Masters,14,Divorced,Other-service,Not-in-family,White,Male,0,0,40,United-States,<=50K.
16275,33,Private,245211,Bachelors,13,Never-married,Prof-specialty,Own-child,White,Male,0,0,40,United-States,<=50K.
16276,39,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States,<=50K.
16277,64,?,321403,HS-grad,9,Widowed,?,Other-relative,Black,Male,0,0,40,United-States,<=50K.
16278,38,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K.
16279,44,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States,<=50K.
16280,35,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,>50K.

In [9]:
### Make some plots ###

In [10]:
# Separate features and targets to pass to ML model
train = data_train.drop('yearly-income',axis=1)
labels = data_train['yearly-income']

In [11]:
train

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States
11,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India
12,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States
13,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States
14,40,Private,121772,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,?
15,34,Private,245487,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico
16,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States
17,32,Private,186824,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States
18,38,Private,28887,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States
19,43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States
20,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States
21,54,Private,302146,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States
22,35,Federal-gov,76845,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States
23,43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States
24,59,Private,109015,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States
25,56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States
26,19,Private,168294,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States
27,54,?,180211,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South
28,39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States
29,49,Private,193366,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32531,30,?,33811,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Female,0,0,99,United-States
32532,34,Private,204461,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States
32533,54,Private,337992,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0,0,50,Japan
32534,37,Private,179137,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,39,United-States
32535,22,Private,325033,12th,8,Never-married,Protective-serv,Own-child,Black,Male,0,0,35,United-States
32536,34,Private,160216,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,55,United-States
32537,30,Private,345898,HS-grad,9,Never-married,Craft-repair,Not-in-family,Black,Male,0,0,46,United-States
32538,38,Private,139180,Bachelors,13,Divorced,Prof-specialty,Unmarried,Black,Female,15020,0,45,United-States
32539,71,?,287372,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States
32540,45,State-gov,252208,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,0,0,40,United-States
32541,41,?,202822,HS-grad,9,Separated,?,Not-in-family,Black,Female,0,0,32,United-States
32542,72,?,129912,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,25,United-States
32543,45,Local-gov,119199,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,0,0,48,United-States
32544,31,Private,199655,Masters,14,Divorced,Other-service,Not-in-family,Other,Female,0,0,30,United-States
32545,39,Local-gov,111499,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States
32546,37,Private,198216,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,White,Female,0,0,40,United-States
32547,43,Private,260761,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,Mexico
32548,65,Self-emp-not-inc,99359,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States
32549,43,State-gov,255835,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States
32550,43,Self-emp-not-inc,27242,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States
32551,32,Private,34066,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States
32552,43,Private,84661,Assoc-voc,11,Married-civ-spouse,Sales,Husband,White,Male,0,0,45,United-States
32553,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan
32554,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States
32555,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States

In [12]:
labels

0         <=50K
1         <=50K
2         <=50K
3         <=50K
4         <=50K
5         <=50K
6         <=50K
7          >50K
8          >50K
9          >50K
10         >50K
11         >50K
12        <=50K
13        <=50K
14         >50K
15        <=50K
16        <=50K
17        <=50K
18        <=50K
19         >50K
20         >50K
21        <=50K
22        <=50K
23        <=50K
24        <=50K
25         >50K
26        <=50K
27         >50K
28        <=50K
29        <=50K
          ...
32531     <=50K
32532      >50K
32533      >50K
32534     <=50K
32535     <=50K
32536      >50K
32537     <=50K
32538      >50K
32539      >50K
32540     <=50K
32541     <=50K
32542     <=50K
32543     <=50K
32544     <=50K
32545      >50K
32546     <=50K
32547     <=50K
32548     <=50K
32549     <=50K
32550     <=50K
32551     <=50K
32552     <=50K
32553     <=50K
32554      >50K
32555     <=50K
32556     <=50K
32557      >50K
32558     <=50K
32559     <=50K
32560      >50K
Name: yearly-income, Length: 32561, dtype: object

In [13]:
# One-hot encode training data: input has to be numerical array
train_encoded = pd.get_dummies(train)

In [14]:
train_encoded

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week,workclass_ ?,workclass_ Federal-gov,workclass_ Local-gov,workclass_ Never-worked,...,native-country_ Portugal,native-country_ Puerto-Rico,native-country_ Scotland,native-country_ South,native-country_ Taiwan,native-country_ Thailand,native-country_ Trinadad&Tobago,native-country_ United-States,native-country_ Vietnam,native-country_ Yugoslavia
0,39,77516,13,2174,0,40,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,50,83311,13,0,0,13,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,38,215646,9,0,0,40,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,53,234721,7,0,0,40,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,28,338409,13,0,0,40,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,37,284582,14,0,0,40,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
6,49,160187,5,0,0,16,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,52,209642,9,0,0,45,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
8,31,45781,14,14084,0,50,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
9,42,159449,13,5178,0,40,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
10,37,280464,10,0,0,80,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
11,30,141297,13,0,0,40,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,23,122272,13,0,0,30,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
13,32,205019,12,0,0,50,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
14,40,121772,11,0,0,40,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,34,245487,4,0,0,45,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,25,176756,9,0,0,35,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
17,32,186824,9,0,0,40,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
18,38,28887,7,0,0,50,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
19,43,292175,14,0,0,45,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
20,40,193524,16,0,0,60,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
21,54,302146,9,0,0,20,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
22,35,76845,5,0,0,40,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
23,43,117037,7,0,2042,40,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
24,59,109015,9,0,0,40,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
25,56,216851,13,0,0,40,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
26,19,168294,9,0,0,40,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
27,54,180211,10,0,0,60,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
28,39,367260,9,0,0,80,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
29,49,193366,9,0,0,40,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32531,30,33811,13,0,0,99,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
32532,34,204461,16,0,0,60,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
32533,54,337992,13,0,0,50,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32534,37,179137,10,0,0,39,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
32535,22,325033,8,0,0,35,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
32536,34,160216,13,0,0,55,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
32537,30,345898,9,0,0,46,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
32538,38,139180,13,15020,0,45,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
32539,71,287372,16,0,0,10,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
32540,45,252208,9,0,0,40,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
32541,41,202822,9,0,0,32,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
32542,72,129912,9,0,0,25,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
32543,45,119199,12,0,0,48,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
32544,31,199655,14,0,0,30,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
32545,39,111499,12,0,0,20,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
32546,37,198216,12,0,0,40,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
32547,43,260761,9,0,0,40,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32548,65,99359,15,1086,0,60,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
32549,43,255835,10,0,0,40,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
32550,43,27242,10,0,0,50,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
32551,32,34066,6,0,0,40,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
32552,43,84661,11,0,0,45,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
32553,32,116138,14,0,0,11,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
32554,53,321865,14,0,0,40,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
32555,22,310152,10,0,0,40,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
32556,27,257302,12,0,0,38,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
32557,40,154374,9,0,0,40,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
32558,58,151910,9,0,0,40,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
32559,22,201490,9,0,0,20,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
32560,52,287927,9,15024,0,40,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [15]:
# Generic ML model from scikit examples
# http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html

In [16]:
from sklearn.datasets import make_classification
X, y = make_classification(n_samples=1000, n_features=4,
                           n_informative=2, n_redundant=0,
                           random_state=0, shuffle=False)
clf = RandomForestClassifier(n_estimators=100, max_depth=2,
                             random_state=0)
clf.fit(X, y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=2, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [17]:
print(clf.feature_importances_)

[ 0.14205973  0.76664038  0.0282433   0.06305659]

In [18]:
print(clf.predict([[0, 0, 0, 0]]))

[1]

In [19]:
# Run ML on income dataset

In [20]:
# Based on Build_model.ipynb in demo-next.datascience.com Optimizing Investment Strategy project
# Ref: http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html
clf = RandomForestClassifier()

# Specify hyperparameter space to optimize
param_dist = {"max_depth": [3, None],
              "max_features": sp_randint(1, 11),
              "min_samples_split": sp_randint(2, 11),
              "min_samples_leaf": sp_randint(1, 11),
              "bootstrap": [True, False],
              "criterion": ["gini", "entropy"]}

In [21]:
# Run randomized grid search
# Ref: http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.RandomizedSearchCV.html
n_iter_search = 10
random_search = RandomizedSearchCV(clf, param_distributions=param_dist, n_iter=n_iter_search)
random_search.fit(train_encoded,labels) # This line builds the model

RandomizedSearchCV(cv=None, error_score='raise',
          estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False),
          fit_params=None, iid=True, n_iter=10, n_jobs=1,
          param_distributions={'bootstrap': [True, False], 'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f93da7c0ed0>, 'min_samples_split': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f93db646110>, 'criterion': ['gini', 'entropy'], 'max_features': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f93da7c0c90>, 'max_depth': [3, None]},
          pre_dispatch='2*n_jobs', random_state=None, refit=True,
          return_train_score=True, scoring=None, verbose=0)

In [22]:
# See model information
random_search.cv_results_ # Etc.

{'mean_fit_time': array([ 0.10392865,  0.39507596,  0.12789551,  0.0882163 ,  0.15210128,
         0.33685033,  0.24483864,  0.23776571,  0.14019608,  0.3299617 ]),
 'mean_score_time': array([ 0.02656221,  0.03553367,  0.06596073,  0.02702459,  0.03125906,
         0.03741511,  0.03392537,  0.03361225,  0.02477272,  0.03737807]),
 'mean_test_score': array([ 0.78676945,  0.85967876,  0.84426154,  0.76115598,  0.8014803 ,
         0.85749823,  0.8523694 ,  0.85427352,  0.79503087,  0.85918737]),
 'mean_train_score': array([ 0.78627794,  0.87091919,  0.85109481,  0.76163204,  0.8043977 ,
         0.883296  ,  0.8602777 ,  0.86075368,  0.79530724,  0.88410986]),
 'param_bootstrap': masked_array(data = [True False True False False False False True False False],
              mask = [False False False False False False False False False False],
        fill_value = ?),
 'param_criterion': masked_array(data = ['gini' 'entropy' 'gini' 'gini' 'entropy' 'entropy' 'entropy' 'entropy'
  'entropy' 'entropy'],
              mask = [False False False False False False False False False False],
        fill_value = ?),
 'param_max_depth': masked_array(data = [3 None None None None None None None 3 None],
              mask = [False False False False False False False False False False],
        fill_value = ?),
 'param_max_features': masked_array(data = [9 10 3 1 1 7 5 8 8 9],
              mask = [False False False False False False False False False False],
        fill_value = ?),
 'param_min_samples_leaf': masked_array(data = [5 10 3 10 3 3 6 8 1 4],
              mask = [False False False False False False False False False False],
        fill_value = ?),
 'param_min_samples_split': masked_array(data = [6 3 5 9 4 7 7 7 10 2],
              mask = [False False False False False False False False False False],
        fill_value = ?),
 'params': [{'bootstrap': True,
   'criterion': 'gini',
   'max_depth': 3,
   'max_features': 9,
   'min_samples_leaf': 5,
   'min_samples_split': 6},
  {'bootstrap': False,
   'criterion': 'entropy',
   'max_depth': None,
   'max_features': 10,
   'min_samples_leaf': 10,
   'min_samples_split': 3},
  {'bootstrap': True,
   'criterion': 'gini',
   'max_depth': None,
   'max_features': 3,
   'min_samples_leaf': 3,
   'min_samples_split': 5},
  {'bootstrap': False,
   'criterion': 'gini',
   'max_depth': None,
   'max_features': 1,
   'min_samples_leaf': 10,
   'min_samples_split': 9},
  {'bootstrap': False,
   'criterion': 'entropy',
   'max_depth': None,
   'max_features': 1,
   'min_samples_leaf': 3,
   'min_samples_split': 4},
  {'bootstrap': False,
   'criterion': 'entropy',
   'max_depth': None,
   'max_features': 7,
   'min_samples_leaf': 3,
   'min_samples_split': 7},
  {'bootstrap': False,
   'criterion': 'entropy',
   'max_depth': None,
   'max_features': 5,
   'min_samples_leaf': 6,
   'min_samples_split': 7},
  {'bootstrap': True,
   'criterion': 'entropy',
   'max_depth': None,
   'max_features': 8,
   'min_samples_leaf': 8,
   'min_samples_split': 7},
  {'bootstrap': False,
   'criterion': 'entropy',
   'max_depth': 3,
   'max_features': 8,
   'min_samples_leaf': 1,
   'min_samples_split': 10},
  {'bootstrap': False,
   'criterion': 'entropy',
   'max_depth': None,
   'max_features': 9,
   'min_samples_leaf': 4,
   'min_samples_split': 2}],
 'rank_test_score': array([ 9,  1,  6, 10,  7,  3,  5,  4,  8,  2], dtype=int32),
 'split0_test_score': array([ 0.76893311,  0.85360236,  0.83932191,  0.75916713,  0.79952091,
         0.85369449,  0.84825871,  0.84945642,  0.80081076,  0.85157546]),
 'split0_train_score': array([ 0.76836965,  0.87156217,  0.85064726,  0.7592021 ,  0.80347353,
         0.88386235,  0.86188787,  0.86248676,  0.80356567,  0.88409269]),
 'split1_test_score': array([ 0.79555924,  0.8594988 ,  0.83803206,  0.76423438,  0.79021559,
         0.85820896,  0.85157546,  0.85415515,  0.78496407,  0.86115718]),
 'split1_train_score': array([ 0.79619478,  0.86944304,  0.84760676,  0.76602018,  0.79260146,
         0.88482978,  0.8629935 ,  0.85995301,  0.78495416,  0.8866725 ]),
 'split2_test_score': array([ 0.79581682,  0.86593569,  0.85543168,  0.76006634,  0.81470561,
         0.86059154,  0.85727449,  0.85920944,  0.79931816,  0.86483   ]),
 'split2_train_score': array([ 0.79426939,  0.87175235,  0.8550304 ,  0.75967385,  0.81711811,
         0.88119587,  0.85595172,  0.85982126,  0.79740188,  0.8815644 ]),
 'std_fit_time': array([ 0.0062069 ,  0.05392896,  0.00183956,  0.00829798,  0.04453542,
         0.05028112,  0.04502873,  0.04831939,  0.04288594,  0.00822232]),
 'std_score_time': array([  1.95845958e-03,   3.62717074e-04,   4.71550498e-02,
          1.68718906e-03,   7.48038738e-04,   2.53023139e-04,
          1.11350467e-04,   1.02540132e-04,   3.08843844e-05,
          2.71612238e-04]),
 'std_test_score': array([ 0.01261292,  0.00503663,  0.00791565,  0.00220754,  0.01009348,
         0.00286019,  0.00372322,  0.0039825 ,  0.0071445 ,  0.0055875 ]),
 'std_train_score': array([ 0.01268745,  0.00104668,  0.00304717,  0.00310885,  0.01003019,
         0.00153664,  0.00309205,  0.00122665,  0.00774113,  0.00208541])}

In [ ]:
### Score model on testing set ###

In [ ]:
### Importances, PDP plots are properties of RF not CV estimator ###